### ISSUE TITLE
Live View - Show multiple Channels 

### ISSUE THREAD

**Issue by JoshHarris2108** [stfc-aeg/odin-pico#5]
Plot multiple channels on the live view canvas graph, for viewing the channels simultaneously

**Comment by JoshHarris2108** [comment]
An idea for improving liveview:
Example of 1000 waveforms of 10K samples requested:
    - Use smaller blocks of say 20 captures
    - after 20 captures display the most recent one in liveview
    - repeat until 1000 waveforms captured
Previous issue encounterd:
    - tried similar idea, saw large overhead setting up picoscope parameters before each small set of captures
Potential idea for soltuion:
    - Have a global "is_changed" flag to represent the settings state of change
    - Use the Put function in the pico_controller to set the status of this flag to true when it is called
    - Maybe in the verify settings function set it to false?
    - only run the pico.setup functions if "is_changed" is true?

In theory, this should reduce the overhead caused by the setup process, after some standalone testing it seems possible to run the setup functions and then run subsiquent run_block calls and it seems to work ok in standalone testing.

Attention would need to be paid to the buffer allocation, and the logic of the rest of the system as the system was initally designed around the idea of re-setting the parameters before each capture.

**Comment by William-Brown5515** [comment]
Closing issue - was sorted through PR #28.
Live-view and PHA now allowed for 1-4 channels.
